modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="thecrabshack" #mandatory
version="${file.jarVersion}" #mandatory
displayName="The Crab Shack" #mandatory
credits="Coda" #optional
description='''This mod adds all sorts of crustaceans!'''